### ISSUE TITLE
.bashrc

### ISSUE THREAD

**Issue by domfarolino** [kurtlewis/.dotfiles#1]
Add .bashrc for some cool non-git things you've aliased maybe? Idk really I just wanted to make an issue on one one of your repos ;)

**Comment by kurtlewis** [comment]
I use zsh, so my aliases are in .zshrc.

This is a point of contention for myself, I've been considering loading aliases separately, so that should I want to load my dotfiles on a machine without zsh I could still use them in bash. I looked up ways to do that and I hadn't decided it was worth it yet.

**Comment by domfarolino** [comment]
Oh yeah lol....I forgot that .zshrc will take reign over bashrc...Even I use this on my macbook can't believe I didn't catch this lol. Nah I'd keep them in zshrc personally, but I understand the conflict.
